export const MOTHER_ROLES = [
    'title',
    'subtitle',
    'logo1',
    'logo2',
    'logo3',
    'photo1',
    'photo2',
    'photo3',
    'photo4',
    'button',
    'sticker1',
    'sticker2',
    'sticker3',
    'price1',
    'price2',
    'description1',
    'description2',
    'shape1',
    'shape2',
    'contact1',
    'contact2',
    'background',
] as const;

export type TMotherRole = typeof MOTHER_ROLES[number];

export const MOTHER_NAMES: Record<TMotherRole, string> = {
    title: _('Title'),
    subtitle: _('Subtitle'),
    logo1: _('Logo 1'),
    logo2: _('Logo 2'),
    logo3: _('Logo 3'),
    photo1: _('Photo 1'),
    photo2: _('Photo 2'),
    photo3: _('Photo 3'),
    photo4: _('Photo 4'),
    button: _('Button'),
    sticker1: _('Sticker 1'),
    sticker2: _('Sticker 2'),
    sticker3: _('Sticker 3'),
    price1: _('Price 1'),
    price2: _('Price 2'),
    description1: _('Description 1'),
    description2: _('Description 2'),
    shape1: _('Shape 1'),
    shape2: _('Shape 2'),
    contact1: _('Contact 1'),
    contact2: _('Contact 2'),
    background: _('Background'),
};
